services:
  mysql:
    image: mysql:8.4
    container_name: leettrack-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leettrack

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: leettrack-app

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/leettrack
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: mysecretkeymysecretkeymysecretkeymysecretkey

volumes:
  mysql-data: